# Generated by Django 4.2.4 on 2023-08-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='name',
            field=models.CharField(default='nadeer', max_length=200),
            preserve_default=False,
        ),
    ]
