# Generated by Django 4.2.4 on 2023-08-20 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_booking_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='breakfast',
        ),
    ]
