# Generated by Django 4.2.4 on 2023-08-21 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0006_booking_breakfast'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.AddField(
            model_name='meal',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meal',
            name='meal_date',
            field=models.DateField(default='2023-01-10'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meal',
            name='food_image',
            field=models.ImageField(blank=True, null=True, upload_to='breakfast/'),
        ),
    ]
