# Generated by Django 4.2.4 on 2023-08-21 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0008_remove_meal_meal_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='meal_date',
            field=models.DateField(default='2023-01-10'),
            preserve_default=False,
        ),
    ]
