# Generated by Django 4.2.4 on 2023-08-25 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0012_alter_order_selected_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.AlterField(
            model_name='order',
            name='selected_date',
            field=models.DateField(),
        ),
    ]
