# Generated by Django 4.2.4 on 2023-08-26 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0013_remove_student_email_alter_order_selected_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='mob_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
