# Generated by Django 4.2.4 on 2023-08-26 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0014_alter_student_mob_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='planner/profile/'),
        ),
    ]
